citra-emu/discord-bot

triggers/github.js
Fixed #3; `triggers/github.js` now parses GitHub Issues correctly, and removes duplicate issues before posting.
It appears that the bug originated from a quirk in JavaScript's `RegExp`, in that `RegExp.prototype.exec` only returns the last found match, regardless of the amount of matches. (See [this StackOverflow answer](http://stackoverflow.com/a/3537914/7650483) for more details.)
The duplicate linking part of this bug appears to have come from not deduplicating matches, some dubious looping, and the fact that discord.js sends messages asynchronously, and thus order is not guaranteed.
=> Find all PR matches and deduplicate

config/default.json
What the title says. I think all 3 can be justified and should be handy.
Untested as usual because lack of test server / documentation and CI.
=> Add more quotes to link to the forum

config/default.json
updated pokemon, and added game command.
=> updated for compatdb

config/default.json
Links to log file guide on forums.
=> added log file command

config/default.json
"performance" to "cpu" and lowered CPU benchmark score from 2,000 to 1,800.
=> changed performance and CPU score

config/default.json
=> "is" to "are"

src/triggers/github.js
Now we no longer have to wonder to ourselves, "but is it _really_ a pull request?"
=> Change CitraBot GitHub message by comment type

src/responses/yuzu.json
Typing 'lenny' will cause it to reply ( ͡° ͜ʖ ͡°), likewise, typing '( ͡° ͜ʖ ͡°)' will cause it to reply 'lenny'.
With this we are closer to ~the singularity~ neobot.
=> Added a lenny command to the canned yuzu responses.

src/responses/citra.json
I'm still not very content with the response for this command, but I guess this is at least better than what we had previously.
If someone has a better idea for the wording of the response, please tell me.
=> Make .alpha describe the current situation a bit more accurately

src/responses/yuzu.json
Please force-push to my branch to fix format-issues. Editing on mobile isn't fun.
**EDIT:** They seem to be fixed now.
=> Add .log command for yuzuBot

src/responses/citra.json
* Renamed `pokemon` to `compat`
* Added `lenny`
=> Modified & added new commands

src/responses/yuzu.json
Reverts citra-emu/discord-bot#46. The problem is fixed.
=> Revert "Add an explanation for PLG's font rendering issue"

src/responses/citra.json
* Command for instructions to obtain AES encryption keys.
=> Add keys command to Citra

src/commands/ban.js
=> Hide some stuff

src/responses/yuzu.json
Update the bot command for .quickstart to better reflect what can be done with the guide.
=> Update the bot command for .quickstart

.gitignore, src/commands/ban.js, src/commands/clearWarnings.js, src/commands/game.js, src/commands/grantDeveloper.js, src/commands/status.js, src/commands/warn.js, src/commands/warnings.js, src/data.js, src/logging.js, src/responses/yuzu.json, src/server.js, src/state.js, src/triggers/github.js
Makes my EsLint plugin happy by fixing most of its warnings.
Most of the changes should be pretty self-explanatory and they are explained in the commit title or dexcription.
=> Fix EsLint warnings and add some files to .gitignore

src/commands/info.js
=> Fix codeblock formatting for mobile

src/responses/yuzu.json
=> Add EA command

src/responses/yuzu.json
=> add .mods command for game-mod database link

src/responses/yuzu.json
Links to this file https://aka.ms/vs/16/release/vc_redist.x64.exe
=> Add vc command for Visual C++2015/2017/2019 Redistributable Package

src/responses/yuzu.json
Canary is not mantained anymore
=> Remove outdated "canary" command (for yuzu)

src/responses/yuzu.json
Adds a command that sends a message to delete the yuzu folder in %localappdata%\yuzu and sends a link to the yuzu installer download page, feel free to change anything if necessary
=> Add appdata command to yuzu bot

src/responses/citra.json
Adds a command to explain how to mod a 3ds, expected use in dumping-support and citra-general
=> Add .mod command

src/responses/yuzu.json
Requested by team members, as this is asked often by users.
=> Adding custom drivers command.
